### ISSUE TITLE
migrate to new architecture

### ISSUE THREAD

**Issue by finnp** [hoodiehq/hoodie-connection-status#46]
part of https://github.com/hoodiehq/hoodie/issues/458

I tried to think of all the steps to migrate this module to the new architecture:

- [x] rename GitHub repository to `hoodie-connection-status`
- [x] move `index.js` to `client/index.js`. I would say we can leave the `lib/` and `test/` folder as they are, as this module only has  client code? 
- [x] add `"browser": "client/index.js"` to the package.json just for convenience, so we can continue to do `require('hoodie-connection-status')`, won’t harm
- [x] rename the `"name"` in `package.json` to `"@hoodie/connection-status"`
- [x] find  `"hoodiehq/hoodie-client-connection-status"` and replace with `"hoodiehq/hoodie-connection-status"` in `package.json`
- [x] find  `"hoodiehq/hoodie-client-connection-status"` and replace with `"hoodiehq/hoodie-connection-status"` in `README.md`
- [x] commit changes with `chore: ...` and `docs: ...` commits. At the end add an empty commit:
- [x] add `"publishConfig": {"access": "public"}` to `package.json` (https://docs.npmjs.com/files/package.json#publishconfig, "Scoped packages default to restricted" https://docs.npmjs.com/cli/access#details)

```
chore: renamed module to @hoodie/connection-status

BREAKING CHANGE:
The repository has been renamed from `hoodie-connection-status` to `@hoodie/connection-status` as part of https://github.com/hoodiehq/hoodie/issues/458
```

- [x] start a PR for review #47

Once merged

- [x] deprecate `hoodie-connection-status` in the npm registry
- [x] enable coveralls for new repo name (run `COVERALLS_REPO_TOKEN=... npm run test:coverage & npm run test:coverage:upload`, then on coveralls.io require `100%` coverage for success)
- [x] update branch protection: re-enable coveralls

**Comment by gr2m** [comment]
great work, LGTM! 

ping @hoodiehq/maintainers for 2nd review :eyes:

**Comment by gr2m** [comment]
ooopsie accidentally merged https://github.com/hoodiehq/hoodie-connection-status/pull/47 so sorry :( if you could still review and LGTM just to be sure that a 2nd pair of eyes looked through it, that would be great!
