### ISSUE TITLE
Bring code coverage to 100%

### ISSUE THREAD

**Issue by seanjohnite** [hoodiehq/hoodie-connection-status#49]
Issued by @gr2m in hoodiehq/hoodie-server-account#100. Also referenced similar issue hoodiehq/hoodie-client-account#66.

**Comment by gr2m** [comment]
Thanks for looking into it Sean!

**Comment by gr2m** [comment]
fixed via #50. Thanks Sean!

**Comment by gr2m** [comment]
nice :) 

<img width="1244" alt="screen shot 2016-03-18 at 14 44 08" src="https://cloud.githubusercontent.com/assets/39992/13888449/ecf11e9e-ed17-11e5-9f7d-540f812b956b.png">
